# Generated by Django 5.0.6 on 2024-08-03 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='изображение')),
                ('description', models.CharField(max_length=300, verbose_name='описание')),
                ('content', models.TextField(verbose_name='контент')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата добавление')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='просмотры')),
                ('is_published', models.BooleanField(default=True, verbose_name='публичность')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to='news.category', verbose_name='категория')),
                ('tags', models.ManyToManyField(related_name='news', to='news.tag', verbose_name='теги')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_link', models.URLField(blank=True, null=True, verbose_name='ссылка сайта')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='ссылка instagrm')),
                ('x_link', models.URLField(blank=True, null=True, verbose_name='ссылка приложении x')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='ссылка facebook')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='ссылка telegram')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='news.news', verbose_name='новость')),
            ],
            options={
                'verbose_name': 'доп. инфо',
                'verbose_name_plural': 'доп. инфы',
            },
        ),
    ]
