# Generated by Django 5.0.6 on 2024-06-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to='news_images/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
