# Generated by Django 5.0.6 on 2024-06-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='просмотры'),
        ),
    ]
