# Generated by Django 5.0.6 on 2024-06-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='публичность'),
        ),
    ]
