# Generated by Django 5.0.6 on 2024-06-27 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_tag_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(related_name='news', to='news.tag', verbose_name='теги'),
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_link', models.URLField(blank=True, null=True, verbose_name='ссылка сайта')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='ссылка instagrm')),
                ('x_link', models.URLField(blank=True, null=True, verbose_name='ссылка приложении x')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='ссылка facebook')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='ссылка telegram')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='news.news', verbose_name='новость')),
            ],
            options={
                'verbose_name': 'доп. инфо',
                'verbose_name_plural': 'доп. инфы',
            },
        ),
    ]
